[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "nexus-quest"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "rich>=13.0.0",
    "quest-engine",
]

[project.scripts]
nexus-quest     = "nexus_quest.main:main_nexus"
terminal-quest  = "nexus_quest.main:main_bash"
git-quest       = "nexus_quest.main:main_git"
docker-quest    = "nexus_quest.main:main_docker"
postgres-quest  = "nexus_quest.main:main_postgres"
vim-quest       = "nexus_quest.main:main_vim"
ssh-quest       = "nexus_quest.main:main_ssh"

[tool.setuptools.packages.find]
where = ["."]
include = ["nexus_quest*"]
