"""
zones.py — AWS skill pack zones for NEXUS.
"""

from engine.zone import Zone
from engine.challenge import Challenge

ZONE_ORDER = [
    "iam_and_security",
    "ec2_and_compute",
    "s3_and_storage",
    "vpc_and_networking",
    "rds_and_databases",
    "lambda_and_serverless",
]

ZONES = {
    "iam_and_security": Zone(
        id="iam_and_security",
        title="IAM and Security",
        description="Manage identities, roles, policies, and access controls in AWS.",
        challenges=[
            Challenge(
                id="aws_iam_principle",
                type="quiz",
                prompt="The principle of least privilege in AWS IAM means:",
                options=[
                    "Give all developers AdministratorAccess for convenience",
                    "Grant only the permissions needed to perform a specific function",
                    "Rotate all passwords every 24 hours",
                    "Use a single shared IAM user for the team",
                ],
                answer="b",
                explanation="Least privilege minimizes blast radius. A compromised key with S3 read-only cannot launch EC2 instances; one with AdministratorAccess can destroy your entire AWS account.",
                xp=10,
            ),
            Challenge(
                id="aws_iam_role_vs_user",
                type="quiz",
                prompt="An EC2 instance needs to access an S3 bucket. The correct approach is:",
                options=[
                    "Hardcode AWS access keys in the application code",
                    "Create an IAM user and put the credentials in an env file on the instance",
                    "Attach an IAM Role with the required S3 permissions to the EC2 instance",
                    "Make the S3 bucket public",
                ],
                answer="c",
                explanation="IAM Roles provide temporary credentials via the instance metadata service — no long-lived keys to manage, rotate, or accidentally expose. This is the AWS-recommended pattern.",
                xp=10,
            ),
            Challenge(
                id="aws_iam_policy_type",
                type="quiz",
                prompt="What is the difference between an AWS Managed Policy and a Customer Managed Policy?",
                options=[
                    "Managed policies are free; customer policies cost extra",
                    "AWS manages and updates AWS Managed Policies; you control Customer Managed Policies",
                    "Managed policies apply cluster-wide; customer policies are region-specific",
                    "There is no functional difference",
                ],
                answer="b",
                explanation="AWS Managed Policies (like AmazonS3ReadOnlyAccess) are maintained by AWS and updated as services evolve. Customer Managed Policies give you full control over permissions with versioning.",
                xp=10,
            ),
            Challenge(
                id="aws_mfa",
                type="fill_blank",
                prompt="The AWS security best practice for the root account is to enable _____ (abbreviated) and never use it for daily tasks.",
                answer="MFA",
                explanation="The AWS root account has unrestricted access to all services. Enable MFA, create IAM users for daily use, and lock root credentials away. A compromised root account cannot be restricted.",
                xp=15,
                hints=["Multi-Factor Authentication"],
            ),
            Challenge(
                id="aws_sts",
                type="quiz",
                prompt="AWS STS (Security Token Service) is used for:",
                options=[
                    "Storing secrets like database passwords",
                    "Issuing temporary, limited-privilege credentials for IAM roles",
                    "Scanning S3 buckets for malware",
                    "Monitoring API calls across all AWS services",
                ],
                answer="b",
                explanation="STS issues temporary credentials (access key, secret key, session token) that expire automatically. AssumeRole uses STS — when an EC2 instance assumes a role, it gets STS credentials.",
                xp=10,
            ),
            Challenge(
                id="aws_cloudtrail",
                type="quiz",
                prompt="AWS CloudTrail records:",
                options=[
                    "CPU and memory metrics for EC2 instances",
                    "All API calls made to AWS services — who did what, when, from where",
                    "Network traffic between VPC subnets",
                    "Application logs from Lambda functions",
                ],
                answer="b",
                explanation="CloudTrail is the audit log for your AWS account. Every API call — `CreateInstance`, `DeleteBucket`, `AssumeRole` — is recorded with the caller identity, time, and source IP. Essential for security investigations.",
                xp=15,
                hints=["Think 'audit trail'"],
            ),
        ],
    ),
    "ec2_and_compute": Zone(
        id="ec2_and_compute",
        title="EC2 and Compute",
        description="Launch, configure, and manage virtual machines in the AWS cloud.",
        challenges=[
            Challenge(
                id="aws_ec2_ami",
                type="quiz",
                prompt="An AMI (Amazon Machine Image) is:",
                options=[
                    "A virtual network interface for EC2 instances",
                    "A template containing an OS, application, and configuration for launching EC2 instances",
                    "An encrypted storage volume attached to an instance",
                    "A load balancer configuration",
                ],
                answer="b",
                explanation="An AMI is a pre-configured snapshot: OS + software + config. You launch instances from AMIs. They enable repeatability — every instance from the same AMI starts in the same known state.",
                xp=10,
            ),
            Challenge(
                id="aws_ec2_instance_types",
                type="quiz",
                prompt="An EC2 instance type like `t3.medium` encodes what information?",
                options=[
                    "The AWS region and availability zone",
                    "The instance family (t=burstable) and size (medium) — CPU/memory ratio",
                    "The storage type and network throughput",
                    "The pricing tier and support level",
                ],
                answer="b",
                explanation="Instance types encode family (t=burstable, c=compute-optimized, m=general, r=memory-optimized) and size. `t3.medium` has 2 vCPU and 4 GiB RAM; `c5.2xlarge` has 8 vCPU and 16 GiB RAM.",
                xp=10,
            ),
            Challenge(
                id="aws_security_groups",
                type="quiz",
                prompt="AWS Security Groups are:",
                options=[
                    "Firewall rules for entire VPCs",
                    "Stateful virtual firewalls that control inbound and outbound traffic to EC2 instances",
                    "Groups of IAM users with shared permissions",
                    "Network ACLs applied at the subnet level",
                ],
                answer="b",
                explanation="Security Groups are stateful — if you allow inbound port 443, the response traffic is automatically allowed outbound. They apply to instances (not subnets, which is NACLs). Default: deny all inbound, allow all outbound.",
                xp=10,
            ),
            Challenge(
                id="aws_key_pairs",
                type="fill_blank",
                prompt="To SSH into an EC2 Linux instance, you authenticate using a key _____. AWS stores the public key; you keep the private key.",
                answer="pair",
                explanation="EC2 key pairs use asymmetric cryptography. AWS injects the public key into the instance at launch; you use the private key file (.pem) to authenticate. If you lose the private key, you lose SSH access.",
                xp=15,
                hints=["Two keys — one public, one private"],
            ),
            Challenge(
                id="aws_user_data",
                type="quiz",
                prompt="EC2 User Data is a script that runs:",
                options=[
                    "Continuously in the background while the instance runs",
                    "Once at first instance launch to bootstrap configuration",
                    "Every time the instance restarts",
                    "On a schedule defined in CloudWatch Events",
                ],
                answer="b",
                explanation="User Data runs once at first launch as root. Use it to install packages, pull code from S3, configure services — bootstrap automation without a configuration management tool.",
                xp=10,
            ),
            Challenge(
                id="aws_elastic_ip",
                type="quiz",
                prompt="Why does a stopped and restarted EC2 instance get a different public IP?",
                options=[
                    "AWS assigns IPs from DHCP which expires on stop",
                    "AWS charges per IP so it reallocates them",
                    "Public IPs are dynamic by default; Elastic IPs are static and must be explicitly allocated",
                    "The instance moves to a different availability zone",
                ],
                answer="c",
                explanation="Public IPs are dynamic — released when an instance stops, reassigned when it starts. An Elastic IP is a static IPv4 address you allocate and associate with an instance, surviving stop/start cycles.",
                xp=15,
                hints=["There's a product called 'Elastic IP' for a reason"],
            ),
        ],
    ),
    "s3_and_storage": Zone(
        id="s3_and_storage",
        title="S3 and Storage",
        description="Store and retrieve any amount of data using Amazon Simple Storage Service.",
        challenges=[
            Challenge(
                id="aws_s3_bucket",
                type="quiz",
                prompt="S3 bucket names must be globally unique because:",
                options=[
                    "AWS limits each account to 100 buckets",
                    "Bucket names are used in the bucket's URL, which must be globally unique",
                    "All S3 buckets share a single partition key",
                    "AWS charges per name uniqueness check",
                ],
                answer="b",
                explanation="Bucket URLs follow the pattern `bucket-name.s3.amazonaws.com`. Since URLs must be unique globally, so must bucket names. This is why `my-bucket` is likely taken — use unique prefixes.",
                xp=10,
            ),
            Challenge(
                id="aws_s3_storage_classes",
                type="quiz",
                prompt="Which S3 storage class is cheapest for data accessed once every few years?",
                options=["S3 Standard", "S3 Intelligent-Tiering", "S3 Glacier Deep Archive", "S3 One Zone-IA"],
                answer="c",
                explanation="S3 Glacier Deep Archive is the lowest-cost S3 storage, designed for data retained for compliance that's rarely accessed. Retrieval time: 12 hours. Use Standard for frequent access, IA for infrequent, Glacier for archival.",
                xp=10,
            ),
            Challenge(
                id="aws_s3_versioning",
                type="quiz",
                prompt="With S3 versioning enabled, deleting an object:",
                options=[
                    "Permanently removes the object and all versions",
                    "Adds a delete marker — previous versions remain and can be restored",
                    "Moves the object to S3 Glacier automatically",
                    "Requires MFA confirmation",
                ],
                answer="b",
                explanation="Versioning inserts a delete marker rather than actually deleting. All previous versions survive. To permanently delete, you must delete each version explicitly (or use lifecycle policies).",
                xp=10,
            ),
            Challenge(
                id="aws_s3_presigned",
                type="fill_blank",
                prompt="To give a user temporary access to a private S3 object without making it public, generate a _____ URL.",
                answer="presigned",
                explanation="Presigned URLs embed temporary credentials that allow accessing a specific object. They expire after a set time and work without AWS credentials on the client side — perfect for sharing private content.",
                xp=15,
                hints=["You're signing the URL in advance", "Pre + signed"],
            ),
            Challenge(
                id="aws_s3_lifecycle",
                type="quiz",
                prompt="An S3 lifecycle rule can automatically:",
                options=[
                    "Scan objects for malware",
                    "Transition objects to cheaper storage classes or expire (delete) them after set periods",
                    "Replicate objects to on-premises storage",
                    "Compress objects to reduce storage costs",
                ],
                answer="b",
                explanation="Lifecycle rules automate cost management. Example: move to IA after 30 days → Glacier after 90 days → delete after 365 days. No manual intervention needed.",
                xp=10,
            ),
            Challenge(
                id="aws_s3_public_block",
                type="quiz",
                prompt="AWS S3 Block Public Access is a setting that:",
                options=[
                    "Prevents outbound S3 transfers above a threshold",
                    "Blocks all public access to buckets regardless of bucket policies or ACLs",
                    "Requires HTTPS for all S3 requests",
                    "Enables encryption on all new objects",
                ],
                answer="b",
                explanation="Block Public Access overrides bucket policies and ACLs — even if a bucket policy grants public access, Block Public Access will deny it. Enable at the account level as a default-secure baseline.",
                xp=15,
                hints=["It's a blanket override, not another policy"],
            ),
        ],
    ),
    "vpc_and_networking": Zone(
        id="vpc_and_networking",
        title="VPC and Networking",
        description="Design and configure isolated networks in AWS with subnets, routing, and gateways.",
        challenges=[
            Challenge(
                id="aws_vpc_definition",
                type="quiz",
                prompt="A VPC (Virtual Private Cloud) provides:",
                options=[
                    "A managed Kubernetes cluster in AWS",
                    "An isolated, logically separated network in AWS where you control IP ranges and routing",
                    "A CDN for distributing content globally",
                    "A VPN connection to your on-premises network",
                ],
                answer="b",
                explanation="A VPC is your own isolated section of the AWS cloud. You control the IP range (CIDR block), subnets, route tables, and internet/NAT gateways. Resources inside a VPC are isolated from other AWS customers.",
                xp=10,
            ),
            Challenge(
                id="aws_public_private_subnet",
                type="quiz",
                prompt="The difference between a public and private subnet in AWS is:",
                options=[
                    "Public subnets have more IP addresses than private ones",
                    "A public subnet has a route to an Internet Gateway; a private subnet does not",
                    "Private subnets require a VPN to access",
                    "Public subnets are accessible from other VPCs by default",
                ],
                answer="b",
                explanation="Subnets are public or private based on routing: if there's a route `0.0.0.0/0 → igw-xxxx` in the route table, it's public. Private subnets route outbound traffic through a NAT Gateway instead.",
                xp=10,
            ),
            Challenge(
                id="aws_nat_gateway",
                type="quiz",
                prompt="A NAT Gateway allows instances in private subnets to:",
                options=[
                    "Receive inbound connections from the internet",
                    "Connect to other VPCs without internet exposure",
                    "Initiate outbound internet connections without being directly accessible from the internet",
                    "Bypass security group rules",
                ],
                answer="c",
                explanation="NAT (Network Address Translation) Gateway translates private IPs to its own public IP for outbound traffic. Private instances can download updates, call APIs — but nothing on the internet can initiate a connection to them.",
                xp=10,
            ),
            Challenge(
                id="aws_cidr",
                type="fill_blank",
                prompt="A VPC with CIDR block `10.0.0.0/16` has _____ available IP addresses.",
                answer="65536",
                explanation="A /16 CIDR has 2^(32-16) = 2^16 = 65,536 IP addresses. AWS reserves 5 per subnet. /16 is a common VPC size; subnets are typically /24 (256 addresses) carved from it.",
                xp=15,
                hints=["2 raised to the power of (32 minus 16)"],
            ),
            Challenge(
                id="aws_security_group_vs_nacl",
                type="quiz",
                prompt="The key difference between Security Groups and Network ACLs (NACLs) is:",
                options=[
                    "Security Groups are free; NACLs are paid",
                    "Security Groups are stateful (per-instance); NACLs are stateless (per-subnet)",
                    "NACLs apply to EC2 only; Security Groups apply to all services",
                    "Security Groups deny by default; NACLs allow by default",
                ],
                answer="b",
                explanation="Security Groups are stateful — track connections, auto-allow responses. NACLs are stateless — evaluate every packet independently, applied at subnet level. NACLs need explicit allow rules for both inbound and return traffic.",
                xp=15,
                hints=["One is stateful, one is stateless"],
            ),
            Challenge(
                id="aws_vpc_peering",
                type="quiz",
                prompt="VPC Peering connects two VPCs so that traffic routes between them:",
                options=[
                    "Via the public internet, encrypted with TLS",
                    "Using the AWS private network backbone — not through the internet",
                    "Through a VPN tunnel that must be manually configured",
                    "Only if both VPCs are in the same AWS account",
                ],
                answer="b",
                explanation="VPC Peering routes traffic privately within AWS. No internet exposure, no bandwidth bottleneck. Limitation: peering is non-transitive — if A peers with B and B peers with C, A cannot reach C through B.",
                xp=10,
            ),
        ],
    ),
    "rds_and_databases": Zone(
        id="rds_and_databases",
        title="RDS and Databases",
        description="Deploy and manage relational databases with Amazon RDS.",
        challenges=[
            Challenge(
                id="aws_rds_purpose",
                type="quiz",
                prompt="Amazon RDS (Relational Database Service) manages:",
                options=[
                    "NoSQL document storage for flexible schemas",
                    "Relational databases with automated backups, patching, and failover",
                    "In-memory caching with Redis and Memcached",
                    "Data warehousing for analytical workloads",
                ],
                answer="b",
                explanation="RDS handles the undifferentiated heavy lifting: OS patching, backups, replication, failover. You focus on the database schema and queries; AWS handles the infrastructure operations.",
                xp=10,
            ),
            Challenge(
                id="aws_rds_multi_az",
                type="quiz",
                prompt="RDS Multi-AZ deployments provide:",
                options=[
                    "Horizontal read scaling across multiple availability zones",
                    "Automatic failover to a standby replica in a different AZ if the primary fails",
                    "Lower storage costs by distributing data across zones",
                    "Global replication to multiple AWS regions",
                ],
                answer="b",
                explanation="Multi-AZ maintains a synchronous standby in a different AZ. If the primary fails, RDS automatically promotes the standby — typically in 60-120 seconds. This is for HA, not read scaling (that's Read Replicas).",
                xp=10,
            ),
            Challenge(
                id="aws_rds_read_replica",
                type="quiz",
                prompt="An RDS Read Replica is used for:",
                options=[
                    "Disaster recovery with automatic failover",
                    "Offloading read queries to improve primary database performance",
                    "Synchronous replication to prevent data loss",
                    "Database encryption at rest",
                ],
                answer="b",
                explanation="Read Replicas use asynchronous replication (slight lag). Direct heavy read traffic (reports, analytics) to replicas to reduce load on the primary. They cannot handle writes and are not automatic failover targets (by default).",
                xp=10,
            ),
            Challenge(
                id="aws_rds_parameter_groups",
                type="fill_blank",
                prompt="To change database engine settings like `max_connections` in RDS, you modify a _____  group.",
                answer="parameter",
                explanation="RDS Parameter Groups contain engine configuration settings. You can't SSH into an RDS instance to edit config files — instead, create a custom parameter group, set your values, and apply it to the RDS instance.",
                xp=15,
                hints=["It's a group of configuration parameters"],
            ),
            Challenge(
                id="aws_rds_backup",
                type="quiz",
                prompt="RDS automated backups allow you to restore to:",
                options=[
                    "Only the last daily backup snapshot",
                    "Any point in time within the backup retention period (up to 35 days)",
                    "A different database engine version",
                    "An on-premises server",
                ],
                answer="b",
                explanation="RDS keeps transaction logs in addition to daily snapshots, enabling point-in-time recovery. Set `backup_retention_period` to 1-35 days. The default is 7 days — set it to 35 for production databases.",
                xp=10,
            ),
            Challenge(
                id="aws_rds_encryption",
                type="quiz",
                prompt="You cannot enable encryption at rest on an existing unencrypted RDS instance. The correct migration path is:",
                options=[
                    "Upgrade the instance to a larger size which enables encryption",
                    "Take a snapshot, copy the snapshot with encryption enabled, restore from the encrypted snapshot",
                    "Enable the `storage_encrypted` parameter in the parameter group",
                    "Run `ALTER DATABASE ... ENCRYPT` in the database engine",
                ],
                answer="b",
                explanation="Encryption can only be enabled at creation time. To encrypt an existing database: take snapshot → copy with encryption → restore. Plan encryption upfront for production databases.",
                xp=15,
                hints=["Snapshots can be copied with different settings"],
            ),
        ],
    ),
    "lambda_and_serverless": Zone(
        id="lambda_and_serverless",
        title="Lambda and Serverless",
        description="Run code without managing servers using AWS Lambda functions.",
        challenges=[
            Challenge(
                id="aws_lambda_definition",
                type="quiz",
                prompt="AWS Lambda is a compute service that:",
                options=[
                    "Manages containerized workloads on dedicated EC2 instances",
                    "Runs code in response to events without provisioning or managing servers",
                    "Provides a managed Kubernetes cluster",
                    "Hosts virtual machines on AWS bare metal",
                ],
                answer="b",
                explanation="Lambda is event-driven serverless compute. You write functions; AWS provisions infrastructure, scales automatically, and charges per 100ms of execution. No servers to patch, no capacity to plan.",
                xp=10,
            ),
            Challenge(
                id="aws_lambda_triggers",
                type="quiz",
                prompt="Which of these can trigger a Lambda function?",
                options=[
                    "Only HTTP requests via API Gateway",
                    "S3 events, DynamoDB streams, API Gateway, SQS messages, CloudWatch Events — and more",
                    "Only scheduled CloudWatch Events",
                    "Only SNS notifications",
                ],
                answer="b",
                explanation="Lambda integrates with most AWS services as an event consumer. S3 object creation, DynamoDB table changes, API calls, SQS messages, scheduled events, Cognito triggers — hundreds of event sources.",
                xp=10,
            ),
            Challenge(
                id="aws_lambda_timeout",
                type="quiz",
                prompt="The maximum execution timeout for a Lambda function is:",
                options=["30 seconds", "5 minutes", "15 minutes", "1 hour"],
                answer="c",
                explanation="Lambda functions have a maximum timeout of 15 minutes (900 seconds). For longer-running workloads, use AWS Fargate, EC2, Step Functions, or break work into smaller functions with SQS between them.",
                xp=10,
            ),
            Challenge(
                id="aws_lambda_cold_start",
                type="fill_blank",
                prompt="The delay experienced when a Lambda function handles its first request after a period of inactivity is called a _____ start.",
                answer="cold",
                explanation="Cold starts occur when AWS must provision a new execution environment. Warm starts reuse existing environments and are much faster. Provisioned Concurrency pre-warms environments to eliminate cold starts for latency-sensitive functions.",
                xp=15,
                hints=["Opposite of 'warm'"],
            ),
            Challenge(
                id="aws_lambda_layers",
                type="quiz",
                prompt="Lambda Layers allow you to:",
                options=[
                    "Run functions across multiple AWS regions simultaneously",
                    "Share code (libraries, dependencies) across multiple Lambda functions without bundling them in each deployment",
                    "Add additional memory beyond the 10 GB limit",
                    "Enable network access from private VPC subnets",
                ],
                answer="b",
                explanation="Layers separate dependencies from function code. A `numpy` layer can be shared across 20 data processing functions — update the layer once, all functions get the update. Also keeps deployment packages small.",
                xp=15,
                hints=["Shared libraries, shared dependencies"],
            ),
            Challenge(
                id="aws_lambda_iam",
                type="quiz",
                prompt="To allow a Lambda function to write to an S3 bucket, you:",
                options=[
                    "Hardcode AWS credentials in the function's environment variables",
                    "Attach an IAM role with S3 write permissions to the Lambda function as its execution role",
                    "Add the Lambda function's ARN to the S3 bucket's ACL",
                    "Enable the Lambda S3 integration in the console",
                ],
                answer="b",
                explanation="Lambda functions use execution roles — IAM roles that define what the function can do. Attach a policy granting `s3:PutObject` to the execution role. No keys needed; credentials are automatically injected.",
                xp=10,
            ),
        ],
    ),
}
