"""
zones.py — Kubernetes skill pack zones for NEXUS.
"""

from engine.zone import Zone
from engine.challenge import Challenge

ZONE_ORDER = [
    "pods_and_deployments",
    "services_and_networking",
    "configmaps_and_secrets",
    "namespaces_and_rbac",
    "helm_charts",
    "cluster_troubleshooting",
]

ZONES = {
    "pods_and_deployments": Zone(
        id="pods_and_deployments",
        title="Pods and Deployments",
        description="Understand the fundamental units of Kubernetes: pods, deployments, and replica sets.",
        challenges=[
            Challenge(
                id="k8s_pod_def",
                type="quiz",
                prompt="In Kubernetes, what is the smallest deployable unit that can be created and managed?",
                options=["A Container", "A Pod", "A Deployment", "A Node"],
                answer="b",
                explanation="A Pod is the smallest deployable unit in Kubernetes. It can contain one or more containers that share network and storage.",
                xp=10,
            ),
            Challenge(
                id="k8s_kubectl_get_pods",
                type="quiz",
                prompt="Which command lists all running pods in the current namespace?",
                options=["kubectl list pods", "kubectl show pods", "kubectl get pods", "kubectl describe pods"],
                answer="c",
                explanation="`kubectl get pods` lists all pods in the current namespace. Add `-A` or `--all-namespaces` to see pods across all namespaces.",
                xp=10,
            ),
            Challenge(
                id="k8s_deployment_purpose",
                type="quiz",
                prompt="What does a Kubernetes Deployment manage?",
                options=[
                    "A single Pod with no restart policy",
                    "A desired state for a set of identical Pods",
                    "Network routing rules between services",
                    "Persistent storage volumes",
                ],
                answer="b",
                explanation="A Deployment manages the desired state of a set of replica Pods. It handles rolling updates, rollbacks, and scaling.",
                xp=10,
            ),
            Challenge(
                id="k8s_replicas",
                type="quiz",
                prompt="A Deployment has `replicas: 3`. One Pod crashes. What does Kubernetes do?",
                options=[
                    "Nothing — the deployment is left with 2 pods",
                    "Alerts an operator to restart manually",
                    "Automatically creates a new Pod to maintain 3 replicas",
                    "Deletes the deployment",
                ],
                answer="c",
                explanation="Kubernetes continuously reconciles desired state with actual state. If a Pod dies, the Deployment controller creates a new one to maintain the specified replica count.",
                xp=10,
            ),
            Challenge(
                id="k8s_apply",
                type="fill_blank",
                prompt="To create or update resources from a YAML file, use: kubectl _____ -f deployment.yaml",
                answer="apply",
                explanation="`kubectl apply -f` creates resources if they don't exist or updates them if they do. It's the standard declarative way to manage Kubernetes resources.",
                xp=15,
                hints=["It's declarative — creates OR updates", "Opposite of 'destroy'"],
            ),
            Challenge(
                id="k8s_rollout",
                type="quiz",
                prompt="You updated a Deployment image. The rollout seems stuck. Which command shows the rollout status?",
                options=[
                    "kubectl status deployment my-app",
                    "kubectl rollout status deployment/my-app",
                    "kubectl get deployment my-app --watch",
                    "kubectl describe rollout my-app",
                ],
                answer="b",
                explanation="`kubectl rollout status deployment/my-app` streams the progress of a deployment rollout, showing how many replicas are updated and ready.",
                xp=15,
                hints=["The verb is 'rollout', not 'status'"],
            ),
        ],
    ),
    "services_and_networking": Zone(
        id="services_and_networking",
        title="Services and Networking",
        description="Route traffic to Pods using Services, DNS, and Ingress controllers.",
        challenges=[
            Challenge(
                id="k8s_service_purpose",
                type="quiz",
                prompt="Why do Kubernetes Pods need a Service to be reliably reachable?",
                options=[
                    "Pods are firewalled by default and can't receive traffic",
                    "Pod IP addresses are ephemeral — they change when Pods restart",
                    "Services provide TLS termination that Pods lack",
                    "Pods run in isolated VLANs",
                ],
                answer="b",
                explanation="Pods get new IP addresses every time they restart. A Service provides a stable virtual IP and DNS name that routes to healthy Pods via label selectors.",
                xp=10,
            ),
            Challenge(
                id="k8s_clusterip",
                type="quiz",
                prompt="Which Service type is only reachable within the cluster (default)?",
                options=["NodePort", "LoadBalancer", "ExternalName", "ClusterIP"],
                answer="d",
                explanation="ClusterIP is the default Service type. It assigns a virtual IP only accessible within the cluster — useful for internal microservice communication.",
                xp=10,
            ),
            Challenge(
                id="k8s_nodeport",
                type="quiz",
                prompt="A NodePort Service exposes port 30080. How do you reach it from outside the cluster?",
                options=[
                    "curl http://cluster-name:30080",
                    "curl http://<any-node-ip>:30080",
                    "curl http://service-name:30080",
                    "You can't — NodePort is internal only",
                ],
                answer="b",
                explanation="NodePort exposes the service on a static port (30000-32767) on every Node's IP. You reach it at `<NodeIP>:<NodePort>` from outside the cluster.",
                xp=10,
            ),
            Challenge(
                id="k8s_ingress",
                type="quiz",
                prompt="What does a Kubernetes Ingress resource define?",
                options=[
                    "How Pods communicate with each other",
                    "HTTP/HTTPS routing rules from external traffic to internal Services",
                    "Network policies blocking traffic between namespaces",
                    "DNS records for cluster-external domains",
                ],
                answer="b",
                explanation="An Ingress defines rules for routing HTTP/HTTPS traffic from outside the cluster to Services. It requires an Ingress controller (like nginx) to implement the rules.",
                xp=10,
            ),
            Challenge(
                id="k8s_dns",
                type="fill_blank",
                prompt="A Service named `api` in namespace `backend` has the internal DNS: api.backend.svc._____",
                answer="cluster.local",
                explanation="Kubernetes DNS follows the pattern `<service>.<namespace>.svc.cluster.local`. The full domain ensures uniqueness across clusters.",
                xp=15,
                hints=["Standard cluster DNS suffix", "Three parts: cluster + local"],
            ),
            Challenge(
                id="k8s_port_forward",
                type="fill_blank",
                prompt="To access a Pod locally at port 8080 without a Service, use: kubectl port-_____ pod/my-pod 8080:80",
                answer="forward",
                explanation="`kubectl port-forward` tunnels traffic from your local machine to a Pod or Service. Useful for debugging without exposing services externally.",
                xp=15,
                hints=["You're forwarding a port", "Not port-tunnel or port-proxy"],
            ),
        ],
    ),
    "configmaps_and_secrets": Zone(
        id="configmaps_and_secrets",
        title="ConfigMaps and Secrets",
        description="Manage application configuration and sensitive data separately from container images.",
        challenges=[
            Challenge(
                id="k8s_configmap_purpose",
                type="quiz",
                prompt="What is the primary purpose of a Kubernetes ConfigMap?",
                options=[
                    "Store encrypted passwords and API keys",
                    "Decouple configuration data from container images",
                    "Define network policies for pods",
                    "Configure node resource limits",
                ],
                answer="b",
                explanation="ConfigMaps store non-sensitive configuration data (env vars, config files, command-line args) separately from images, making apps portable across environments.",
                xp=10,
            ),
            Challenge(
                id="k8s_secret_encoding",
                type="quiz",
                prompt="Kubernetes Secrets store values as base64. What does this mean for security?",
                options=[
                    "Values are encrypted at rest by default",
                    "Values are obfuscated but NOT encrypted — anyone with API access can read them",
                    "Values are hashed and irreversible",
                    "Values require a decryption key to view",
                ],
                answer="b",
                explanation="Base64 is encoding, not encryption. Secrets are obfuscated for transport but NOT secure by default. Use etcd encryption or external secret managers (Vault, AWS Secrets Manager) for real security.",
                xp=10,
            ),
            Challenge(
                id="k8s_env_from",
                type="quiz",
                prompt="To inject ALL keys from a ConfigMap as environment variables, you use:",
                options=[
                    "env.name: configMapRef",
                    "envFrom: - configMapRef: name: my-config",
                    "volumes.configMap: my-config",
                    "inject.configMap: all: true",
                ],
                answer="b",
                explanation="`envFrom` with `configMapRef` injects all ConfigMap keys as environment variables. Individual keys use `env` with `valueFrom.configMapKeyRef`.",
                xp=10,
            ),
            Challenge(
                id="k8s_secret_create",
                type="fill_blank",
                prompt="Create a generic secret from literal values: kubectl create secret _____ db-creds --from-literal=password=s3cr3t",
                answer="generic",
                explanation="The three secret types are `generic` (arbitrary key-value), `docker-registry` (image pull secrets), and `tls` (TLS cert/key pairs).",
                xp=15,
                hints=["It's for arbitrary key-value pairs", "Not 'tls' or 'docker-registry'"],
            ),
            Challenge(
                id="k8s_volume_mount",
                type="quiz",
                prompt="A ConfigMap contains a file `app.conf`. The best way to make it available inside a container is:",
                options=[
                    "Inject it as an environment variable",
                    "Mount it as a Volume at a path like /etc/config/app.conf",
                    "Encode it in the container's CMD",
                    "Store it in a Secret instead",
                ],
                answer="b",
                explanation="Files in ConfigMaps (or Secrets) are best mounted as Volumes. Each key becomes a file in the mount path. Env vars work for short strings but not for multi-line config files.",
                xp=10,
            ),
            Challenge(
                id="k8s_immutable_configmap",
                type="quiz",
                prompt="Setting `immutable: true` on a ConfigMap does what?",
                options=[
                    "Encrypts the ConfigMap data",
                    "Prevents the ConfigMap from being deleted",
                    "Prevents updates, improving cluster performance for large ConfigMaps",
                    "Makes the ConfigMap cluster-wide instead of namespace-scoped",
                ],
                answer="c",
                explanation="Immutable ConfigMaps/Secrets prevent accidental updates and allow the kubelet to stop watching them, reducing API server load. Useful for configs that should never change.",
                xp=15,
                hints=["It's about performance as well as safety"],
            ),
        ],
    ),
    "namespaces_and_rbac": Zone(
        id="namespaces_and_rbac",
        title="Namespaces and RBAC",
        description="Organize cluster resources and control access with Role-Based Access Control.",
        challenges=[
            Challenge(
                id="k8s_namespace_purpose",
                type="quiz",
                prompt="Kubernetes namespaces provide:",
                options=[
                    "Network isolation between Pods by default",
                    "A scope for names — the same resource name can exist in multiple namespaces",
                    "Guaranteed CPU and memory allocation",
                    "Encryption for all resources within them",
                ],
                answer="b",
                explanation="Namespaces partition the cluster's name space — two Deployments named `api` can exist in different namespaces. They don't provide network isolation by default (that's NetworkPolicy).",
                xp=10,
            ),
            Challenge(
                id="k8s_default_namespaces",
                type="quiz",
                prompt="Which namespace contains Kubernetes system components like kube-dns and kube-proxy?",
                options=["default", "kube-system", "kube-public", "cluster-admin"],
                answer="b",
                explanation="`kube-system` contains critical cluster components. `default` is for user workloads with no explicit namespace. `kube-public` is readable by all, used for cluster info.",
                xp=10,
            ),
            Challenge(
                id="k8s_rbac_role",
                type="quiz",
                prompt="What is the difference between a Role and a ClusterRole in RBAC?",
                options=[
                    "Roles have more permissions than ClusterRoles",
                    "A Role is namespace-scoped; a ClusterRole applies cluster-wide",
                    "ClusterRoles require multi-factor authentication",
                    "Roles use JSON; ClusterRoles use YAML",
                ],
                answer="b",
                explanation="Roles define permissions within a single namespace. ClusterRoles define permissions across the entire cluster (or for cluster-scoped resources like Nodes).",
                xp=10,
            ),
            Challenge(
                id="k8s_rolebinding",
                type="quiz",
                prompt="A RoleBinding connects:",
                options=[
                    "Two Services in different namespaces",
                    "A Role or ClusterRole to a user, group, or ServiceAccount",
                    "A Pod to its ConfigMap",
                    "A Deployment to its ReplicaSet",
                ],
                answer="b",
                explanation="A RoleBinding grants the permissions defined in a Role to a subject (user, group, or ServiceAccount). Without a binding, a Role has no effect.",
                xp=10,
            ),
            Challenge(
                id="k8s_service_account",
                type="fill_blank",
                prompt="Every Pod runs as a ServiceAccount. If not specified, it uses the _____ ServiceAccount in its namespace.",
                answer="default",
                explanation="The `default` ServiceAccount exists in every namespace. It's best practice to create dedicated ServiceAccounts with minimal permissions rather than using default.",
                xp=15,
                hints=["It's the most basic, unremarkable name"],
            ),
            Challenge(
                id="k8s_least_privilege",
                type="quiz",
                prompt="The principle of least privilege in RBAC means:",
                options=[
                    "Use ClusterAdmin for all service accounts to avoid permission errors",
                    "Grant only the minimum permissions needed to perform a function",
                    "Rotate service account tokens every hour",
                    "Disable RBAC for internal services",
                ],
                answer="b",
                explanation="Least privilege limits blast radius if a Pod is compromised. A compromised Pod with ClusterAdmin can destroy the entire cluster; one with read-only namespace permissions cannot.",
                xp=15,
                hints=["Less is more — for security"],
            ),
        ],
    ),
    "helm_charts": Zone(
        id="helm_charts",
        title="Helm Charts",
        description="Package, version, and deploy Kubernetes applications using the Helm package manager.",
        challenges=[
            Challenge(
                id="k8s_helm_purpose",
                type="quiz",
                prompt="What is Helm in the Kubernetes ecosystem?",
                options=[
                    "A monitoring tool for cluster metrics",
                    "A package manager that templates and manages Kubernetes manifests",
                    "A network policy engine",
                    "A container runtime alternative to Docker",
                ],
                answer="b",
                explanation="Helm is Kubernetes' package manager. It bundles related manifests into Charts, supports templating with values, and tracks release history for upgrades and rollbacks.",
                xp=10,
            ),
            Challenge(
                id="k8s_helm_install",
                type="fill_blank",
                prompt="Install a chart named `nginx-ingress` from the `ingress-nginx` repo with release name `ingress`: helm _____ ingress ingress-nginx/nginx-ingress",
                answer="install",
                explanation="`helm install <release-name> <chart>` deploys a chart. The release name identifies this specific installation and is used for upgrades and rollbacks.",
                xp=10,
            ),
            Challenge(
                id="k8s_helm_values",
                type="quiz",
                prompt="In a Helm chart, where are default configuration values defined?",
                options=["Chart.yaml", "values.yaml", "templates/deployment.yaml", "requirements.yaml"],
                answer="b",
                explanation="`values.yaml` holds default values that templates reference with `{{ .Values.key }}`. Users can override them with `--set key=value` or `-f custom-values.yaml`.",
                xp=10,
            ),
            Challenge(
                id="k8s_helm_upgrade",
                type="fill_blank",
                prompt="Update a running release to a new chart version: helm _____ my-app ./my-chart --set image.tag=v2.0",
                answer="upgrade",
                explanation="`helm upgrade` applies changes to an existing release. Combined with `--install`, it creates the release if it doesn't exist (`helm upgrade --install`).",
                xp=15,
                hints=["The opposite of 'downgrade'"],
            ),
            Challenge(
                id="k8s_helm_rollback",
                type="quiz",
                prompt="After a bad deployment, how do you revert to the previous Helm release?",
                options=[
                    "kubectl rollout undo deployment/my-app",
                    "helm revert my-release",
                    "helm rollback my-release",
                    "helm history my-release --revert",
                ],
                answer="c",
                explanation="`helm rollback <release> [revision]` reverts to a previous release revision. `helm history <release>` shows all revisions available to roll back to.",
                xp=15,
                hints=["Think of it like git rollback"],
            ),
            Challenge(
                id="k8s_helm_chart_yaml",
                type="quiz",
                prompt="The `Chart.yaml` file in a Helm chart contains:",
                options=[
                    "Kubernetes resource definitions",
                    "Template helper functions",
                    "Chart metadata: name, version, description, dependencies",
                    "Default configuration values",
                ],
                answer="c",
                explanation="`Chart.yaml` is the chart's metadata file — it defines the name, version, apiVersion, description, and dependencies (sub-charts). It's required for every Helm chart.",
                xp=10,
            ),
        ],
    ),
    "cluster_troubleshooting": Zone(
        id="cluster_troubleshooting",
        title="Cluster Troubleshooting",
        description="Diagnose and fix failing Pods, stuck deployments, and misconfigured resources.",
        challenges=[
            Challenge(
                id="k8s_pod_pending",
                type="quiz",
                prompt="A Pod is stuck in `Pending` state. What is the most likely cause?",
                options=[
                    "The container image is crashing on startup",
                    "The Pod cannot be scheduled — insufficient resources or no matching node",
                    "The liveness probe is failing",
                    "The ConfigMap it references doesn't exist",
                ],
                answer="b",
                explanation="Pending means the scheduler can't place the Pod on a Node. Check `kubectl describe pod <name>` for events — common causes: insufficient CPU/memory, node selectors, taints.",
                xp=10,
            ),
            Challenge(
                id="k8s_crashloopbackoff",
                type="quiz",
                prompt="A Pod shows `CrashLoopBackOff`. This means:",
                options=[
                    "The Pod is waiting for a dependent service to start",
                    "The container starts, crashes, and Kubernetes keeps restarting it with delays",
                    "The Pod was evicted due to memory pressure",
                    "Network connectivity to the Pod is broken",
                ],
                answer="b",
                explanation="CrashLoopBackOff means the container is repeatedly crashing. Kubernetes backs off restart attempts exponentially. Check logs with `kubectl logs <pod> --previous` to see crash output.",
                xp=10,
            ),
            Challenge(
                id="k8s_logs",
                type="fill_blank",
                prompt="View logs from a crashed container's previous run: kubectl logs my-pod --_____",
                answer="previous",
                explanation="`--previous` (or `-p`) shows logs from the last terminated container instance — essential for debugging CrashLoopBackOff since the current container may have just started.",
                xp=15,
                hints=["You want the run before the current one"],
            ),
            Challenge(
                id="k8s_describe",
                type="quiz",
                prompt="Which command gives the most complete diagnostic view of a Pod including events?",
                options=[
                    "kubectl get pod my-pod -o yaml",
                    "kubectl logs my-pod",
                    "kubectl describe pod my-pod",
                    "kubectl inspect pod my-pod",
                ],
                answer="c",
                explanation="`kubectl describe` shows full resource details including Events — the 'Recent Events' section at the bottom shows scheduling failures, image pull errors, and probe failures.",
                xp=10,
            ),
            Challenge(
                id="k8s_exec",
                type="fill_blank",
                prompt="Run an interactive shell inside a running container: kubectl _____ -it my-pod -- /bin/sh",
                answer="exec",
                explanation="`kubectl exec -it <pod> -- <command>` runs a command inside a container. The `-it` flags attach an interactive terminal. Essential for live debugging.",
                xp=15,
                hints=["Like `docker exec`"],
            ),
            Challenge(
                id="k8s_oom",
                type="quiz",
                prompt="A Pod was killed with `OOMKilled` exit code. The fix is:",
                options=[
                    "Increase the Pod's CPU limit",
                    "Increase the Pod's memory limit or reduce memory usage",
                    "Add more replicas to the Deployment",
                    "Enable swap on the node",
                ],
                answer="b",
                explanation="OOMKilled means Out Of Memory — the container exceeded its memory limit. Either increase `resources.limits.memory` in the Pod spec or optimize the application's memory usage.",
                xp=15,
                hints=["OOM = Out Of Memory"],
            ),
        ],
    ),
}
